### ISSUE TITLE
[v10] IPN and return url doesn't work with accented characters

### ISSUE THREAD

**Issue by zeroheure** [payzen/odoo#2]
Title says all. Try to enter accented characters in Odoo form. Payment notification fails with this error message:
...............
[strip non payzen lines]
File "/var/lib/odoo/addons/10.0/payment_payzen/models/payzen.py", line 193, in _payzen_form_get_tx_from_data
    shasign_check = tx.acquirer_id._payzen_generate_digital_sign('out', data)
File "/var/lib/odoo/addons/10.0/payment_payzen/models/payzen.py", line 43, in _payzen_generate_digital_sign
    signature += str(vads_values[key]).decode('utf-8') + '+'
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
..............

A quick and dirty hack prove this is an encoding problem: 
in `payzen_tx_values.update` change `encode('utf-8')` to `encode('ascii', errors='ignore')`
then everythings works well.

**Comment by zeroheure** [comment]
Update : `_payzen_generate_digital_sign` works the first time, before sending datas to Payzen. It is _only_ the second and third time, after payment has been made, that there is an error, i.e. on IPN and return. The error is _allways_ with the character in position one, wherever I type an accented letter.

**Comment by zeroheure** [comment]
Here's the types in the vads_values dictionnary:

odoo.addons.payment_payzen.models.payzen: ('vads_action_mode', 'INTERACTIVE', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_amount', 7490, <type 'int'>)
odoo.addons.payment_payzen.models.payzen: ('vads_contrib', 'Odoo10_0.9.1/10.0-20170414', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_ctx_mode', 'TEST', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_currency', 978, <type 'int'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_address', 'b\xc3\xa9po', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_city', 'b\xc3\xa9po', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_country', u'FR', <type 'unicode'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_email', 'postmaster@alternatif.org', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_first_name', '', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_last_name', 'b\xc3\xa9po', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_name', 'b\xc3\xa9po', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_phone', '123', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_state', '', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_cust_zip', '23', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_order_id', '/', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_page_action', 'PAYMENT', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_payment_config', 'SINGLE', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_return_mode', 'GET', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_site_id', u'16793461', <type 'unicode'>)
odoo.addons.payment_payzen.models.payzen: ('vads_trans_date', '20170427092129', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_trans_id', '336890', <type 'str'>)
odoo.addons.payment_payzen.models.payzen: ('vads_url_return', u'http://178.33.255.152:8069/payment/payzen/return', <type 'unicode'>)

**Comment by zeroheure** [comment]
Please, add this debug code after the closing line of payzen_tx_values.update() dictionary : 
```python
        # check dict values type for debug
        for key,val in sorted(payzen_tx_values.items()):
             type_tx_values_msg = key, type(key), val, type(val)
             _logger.error(type_tx_values_msg)
```
You will see that the problem comes from the getting of vads_ values. 
e.g. while Odoo gives `partner_name` in unicode `vads_cust_name` is stored in str like in:
```python
'vads_cust_name': values.get('partner_name') and values.get('partner_name')[0:126].encode('utf-8') or ''
```

**Comment by nabil509** [comment]
Thank you for your feedback. 

Yes, there is a problem in encoding of data passed to _payzen_generate_digital_sign method. I just pushed changes to develop branch to improve module and fix that problem. 

All data passed to _payzen_generate_digital_sign  must be unicode. So we can use the same method to compute signature for both payment request and response.

We finish our tests shortly and the new version will be released.

**Comment by zeroheure** [comment]
Thanks Nabil. I will test myself too.
I work for the Payzen customer "Chez les enfants". I've asked Payzen support to forward my emails to you. But I don't know if they did so.

**Comment by zeroheure** [comment]
Tested. It works! thanks.
We will now conduct extensive tests using
Ubuntu and Debian using Firefox, Chrome, Chromium and Gnome's Web (webkit2)
Windows 7 using IExplorer 11 (2013)

**Comment by nabil509** [comment]
Cool ! Thank you for your action. 

Yes, I have received your e-mails and they were very usefull for me since you gave many traces on the problem. Thank you again.

**Comment by zeroheure** [comment]
Problem for cleaner bug reports was that I'm an experienced sysadmin but a total noob in object programming. I love only procedural Perl ! :-)

**Comment by nabil509** [comment]
Bug fixed, I close issue.
