### ISSUE TITLE
move reference dicts in an external file.

### ISSUE THREAD

**Issue by zeroheure** [payzen/odoo#4]
I suggest to move the 2 dictionaries payzen_currencies{} and _AUTH_RESULT {} in an external file.
It will ease updates and errors i10n
Check Ogone payment module for an example (file ogone.py in data folder)

**Comment by nabil509** [comment]
Very good suggestion. I will do it for this release for _AUTH_RESULT and for the next release payzen_currencies.

**Comment by nabil509** [comment]
Done, I close issue.
