### ISSUE TITLE
size of country code not checked

### ISSUE THREAD

**Issue by zeroheure** [payzen/odoo#6]
in `models/payment.py/tx_values.update()` country code size is not limited.
```python
'vads_cust_country': values.get('billing_partner_country').code and values.get('billing_partner_country').code.upper() or '',
```
should be
```python
'vads_cust_country': values.get('billing_partner_country').code and values.get('billing_partner_country').code[0:4].upper() or '',
```
same for `vads_ship_to_country` value.

**Comment by nabil509** [comment]
Country code is quite 2 characters. It come from Odoo res_country.code column that is well formed. The check is not necessary.

**Comment by zeroheure** [comment]
OK, I though it was coming from the form value.
